echo "////    Auto-generated by symbol_gen.sh. DO NOT EDIT!" >$2
echo "#include \"symbol.h\"" >>$2
echo "const symbol_t __symbol_tab[] = {" >>$2
nm $1 | grep -i " t " | awk '{ print "    { .address = (unsigned int)0x"$1", .name = \""$3"\" }," }' | sort >>$2
echo "    { .address = (unsigned int)0xffffffff, .name = \"\" }};" >>$2

# calculate the size of the symbol table array inline
SIZE=$(nm $1 | grep -i " t " | wc -l)
echo "const unsigned int __symbol_tab_size = $SIZE;" >>$2
