
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_ASM_COMPILER_WORKS TRUE)

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "x86-64")

set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
set(CMAKE_CROSSCOMPILING TRUE)

if(APPLE)
  set(CMAKE_C_COMPILER x86_64-elf-gcc)
  set(CMAKE_CXX_COMPILER x86_64-elf-g++)
  set(CMAKE_ASM_COMPILER x86_64-elf-gcc)
  set(LINKER x86_64-elf-ld)

  unset(CMAKE_OSX_ARCHITECTURES CACHE) # Remove macOS-specific architectures
  unset(CMAKE_COLOR_DIAGNOSTICS CACHE)
  set(APPLE FALSE)

  set(CMAKE_C_FLAGS "")
  set(CMAKE_CXX_FLAGS "")
  set(CMAKE_ASM_FLAGS "")

  set(HAVE_FLAG_SEARCH_PATHS_FIRST 0)
  set(CMAKE_C_LINK_FLAGS "")
  set(CMAKE_CXX_LINK_FLAGS "")
else()
  set(TOOLCHAIN ${CMAKE_CURRENT_LIST_DIR})

  set(LINKER ${TOOLCHAIN}/bin/i386-elf-ld)
  set(CMAKE_C_COMPILER ${TOOLCHAIN}/bin/i386-elf-gcc)
  set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/i386-elf-g++)
  set(CMAKE_ASM_COMPILER ${TOOLCHAIN}/bin/i386-elf-gcc)
endif()

# set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
# set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")