if(APPLE)
  set(CMAKE_C_COMPILER x86_64-elf-gcc)
  set(CMAKE_CXX_COMPILER x86_64-elf-g++)
  set(CMAKE_ASM_COMPILER x86_64-elf-gcc)
  set(LINKER x86_64-elf-ld)

  unset(CMAKE_OSX_ARCHITECTURES CACHE) # Remove macOS-specific architectures
  unset(CMAKE_COLOR_DIAGNOSTICS CACHE)
  set(CMAKE_SYSTEM_NAME Generic) # Prevents macOS-specific defaults
  set(APPLE FALSE)

  set(CMAKE_C_FLAGS "")
  set(CMAKE_CXX_FLAGS "")
  set(CMAKE_ASM_FLAGS "")

  set(HAVE_FLAG_SEARCH_PATHS_FIRST 0)
  set(CMAKE_C_LINK_FLAGS "")
  set(CMAKE_CXX_LINK_FLAGS "")
else()
  set(LINKER ${TOOLCHAIN}/bin/i386-elf-ld)
  set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
  set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

  set(CMAKE_C_COMPILER ${TOOLCHAIN}/bin/i386-elf-gcc)
  set(CMAKE_CXX_COMPILER ${TOOLCHAIN}/bin/i386-elf-g++)
  set(CMAKE_ASM_COMPILER ${TOOLCHAIN}/bin/i386-elf-gcc)
endif()

set(CMAKE_CXX_COMPILER_TARGET "i386" CACHE INTERNAL "" FORCE)
set(CMAKE_C_COMPILER_TARGET "i386" CACHE INTERNAL "" FORCE)
set(CMAKE_ASM_COMPILER_TARGET "i386" CACHE INTERNAL "" FORCE)